---
- name: Create the rethinkdb data directory
  file: dest={{ rethinkdb_directory }} mode=755 owner={{ rethinkdb_user }} group={{ rethinkdb_group }} state=directory

- name: Check if the rethinkdb data directory already exists
  action: shell test -d {{ rethinkdb_directory }}/{{ inventory_hostname }} && echo "exists" || echo ""
  register: rethinkdb_directory_exists

- name: Create the rethinkdb data folder using the rethinkdb create command
  command: rethinkdb create --runuser {{ rethinkdb_user }} --rungroup {{ rethinkdb_group }} -d {{ rethinkdb_directory }}/{{ inventory_hostname }}
  when: ${rethinkdb_directory_exists.stdout} != "exists"

- name: Create the rethinkdb config file
  template: src=rethinkdb.conf.j2 dest=/etc/rethinkdb/instances.d/{{ inventory_hostname }}.conf
  notify: restart rethinkdb

- name: Ensure rethinkdb is running automatically at boot time
  action: command /sbin/chkconfig rethinkdb on
